FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json .

RUN npm install 

COPY . .

RUN npm run build

FROM nginx
Expose 3000
COPY ./nginx/deafault.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/builder /user/share/nginx/html
